# Copyright (c) Facebook, Inc. and its affiliates.
from .maskformer_transformer_decoder import StandardTransformerDecoder
from .mask2former_transformer_decoder import MultiScaleMaskedTransformerDecoder
# Versión con QueryFineTuner
from .mask2former_transformer_decoder_QSM_V3 import MultiScaleMaskedTransformerDecoderQueryFineTuner

# Pruebas de attention
from .mask2former_transformer_decoder_biformer_attention import MultiScaleMaskedTransformerWithBilevelRoutingAttentionDecoder
#from .mask2former_transformer_decoder_sparse_attention import MultiScaleMaskedTransformerWithSparseAttentionDecoder
from .mask2former_transformer_decoder_sparse2nd import MultiScaleMaskedTransformerWithSparseAttentionDecoder_2nd
from .mask2former_transformer_decoder_QSM_V3_Biformer_Attention import MultiScaleMaskedTransformerDecoderQueryFineTunerBiformerAttention


# Pruebas nuevos mecanismo de atencion
from .mask2former_transformer_decoder_cc_attention import MultiScaleMaskedTransformerDecoderCrissCrossAttention
from .mask2former_transformer_decoder_axial_attention import MultiScaleMaskedTransformerDecoderAxialAttention
from .mask2former_transformer_decoder_CBAM_attention import MultiScaleMaskedTransformerDecoderCBAMAttention